### ISSUE TITLE
Support for longer song titles

### ISSUE THREAD

**Issue by ajmeese7** [novatorem/novatorem#3]
![Long song title](https://user-images.githubusercontent.com/17814535/90980189-810bc300-e51f-11ea-8faa-91b12d083fb2.png)

When the song title wraps and becomes two lines long, the bars remain in the same place and obscure the artist text. It would be great if the bars weren't absolutely positioned for when the text wraps, if it's possible to manage that while keeping the same look for the project.

Love your work so far, keep it up! Cheers.

**Comment by novatorem** [comment]
Good catch! Fixed in https://github.com/novatorem/novatorem/commit/ad63ff53c764a5b0633375dcbc1adcccccb1893e.

Before:
![image](https://user-images.githubusercontent.com/16753077/90980964-5411dd00-e52c-11ea-9fab-c2e1c84027a9.png)

Now:
![image](https://user-images.githubusercontent.com/16753077/90984258-da84e980-e541-11ea-8f71-5de47c5ad528.png)


I think it would be better to limit the height, so people don't have to accommodate the now playing widget. If you have a specific/better idea - let me know.
